apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ovn-mac-unlock.yaml
configMapGenerator:
  - name: ovn-mac-unlock
    files:
      - ovn-mac-unlock.sh
